solar:
  greeting: Welcome to the book catalog from Kubernetes 👋
spring:
  datasource:
    url: jdbc:postgresql://solar-postgres/solardb_catalog
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://solar-keycloak/realms/SolarBookshop